### ISSUE TITLE
Consider defaulting RowEnding to Detect

### ISSUE THREAD

**Issue by MarkPflug** [kevin-montrose/Cesil#42]
I was experimenting with Cesil after reading the performance blog post you wrote recently. It took me a while (longer than I'd like to admit) to realize that the reason that `EnumerateAll` was not producing any results was because the file I was trying to read used '\n' for newlines, but Options defaults to `CarriageReturnLineFeed`. For the sanity of future users, you might consider changing the default to `Detect` instead.

The dataset I was using was the JHU covid-19 dataset available [here](
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/f7c2384622806d5297d16c314a7bc0b9cde24937/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv)
I was trying to bind it to the following class:
```
	public class CovidRecord
	{
		public int UID { get; set; }
		public string iso2 { get; set; }
		public string iso3 { get; set; }
		public int? code3 { get; set; }
		public float? FIPS { get; set; }
		public string Admin2 { get; set; }
		public string Province_State { get; set; }
		public string Country_Region { get; set; }
		public float? Lat { get; set; }
		public float? Long_ { get; set; }
		public string Combined_Key { get; set; }
	}
```

I have also authored a CSV library for .NET: [Sylvan.Data.Csv](https://github.com/MarkPflug/Sylvan/blob/master/docs/Sylvan.Data.Csv.md). My focus was primarily performance, and I've put together some [benchmarks](https://github.com/MarkPflug/CsvBenchmarks/blob/main/docs/Benchmarks.md) for a handful of CSV libraries I could find. Sylvan exposes csv data a DbDataReader only, and doesn't provide any object binding capabilities, so comparing it to Cesil wouldn't exactly be apples to apples; as at least as far as I could tell Cesil only allows binding to objects.

**Comment by kevin-montrose** [comment]
Yeah, I've gone back and forth on defaults for `RowEnding` - technically it costs a bit more to do detect, but practically it seems like a common enough stumbling block to change.

There's one bit of subtlty, right now `RowEnding` is shared between read & write - but writing "Detect" makes no sense, so first I'd need to split `RowEnding` into two different options.

I'll try and get that in before the next update - though in the immediate future I'm mostly going to be working on source generator support.

**Comment by MarkPflug** [comment]
Writing "detect" could make sense if you interpret it to mean "platform default", so `\r\n` on windows and `\n` otherwise? That would probably match most users expectations too.
