### ISSUE TITLE
Alternatives to IEnumerable<DynamicCellValue> for ITypeDescriber.GetCellsForDynamicRow

### ISSUE THREAD

**Issue by kevin-montrose** [kevin-montrose/Cesil#6]
This was posed in [Overthinking CSV With Cesil: Writing Dynamic Types](https://kevinmontrose.com/2020/06/16/overthinking-csv-with-cesil-writing-dynamic-types/).

[`ITypeDescriber.GetCellsForDynamicRow(in WriteContext, object)`](https://github.com/kevin-montrose/Cesil/blob/5a1ec906fb2672b1b0111ca7fe69a3d2e7183ec4/Cesil/TypeDescriber/ITypeDescriber.cs#L58) is invoked once per row when writing dynamic types.  While a client could (in theory) reuse the allocated `IEnumerable<T>` across multiple calls, this is difficult (bordering on impossible) in the general case because when the returned value is no longer in use is impossible to know.  As a consequence, the natural way to implement `GetCellsForDynamicRow()` requires at least one heap allocation per call (in fact, this is what [`DefaultTypeDescriber`](https://github.com/kevin-montrose/Cesil/blob/5a1ec906fb2672b1b0111ca7fe69a3d2e7183ec4/Cesil/TypeDescriber/DefaultTypeDescriber.cs#L760) does).

**Is there an alternative method (or methods) / return type / etc. that would allow for no allocation implementations of `GetCellsForDynamicRow`'s functionality**?

**Comment by benjamin-hodgson** [comment]
paraphrasing a discussion in chat:

I suggested something along the lines of [my `IRewritable` design](https://www.benjamin.pizza/posts/2019-10-05-rewriting-irewritable.html#the-new-way)

```csharp
int CountCellsForDynamicRow(in WriteContext writeContext, object row);
// copy the cells into the output span
void GetCellsForDynamicRow(in WriteContext writeContext, object row, Span<DynamicCellValue> output);
```

so the calling code would look something like (pseudocode):

```csharp
var count = describer.CountCellsForDynamicRow(writeContext, row);
var buffer = ArrayPool.Get(count);
describer.GetCellsForDynamicRow(writeContext, row, buffer.AsSpan().Slice(0, count));

// do something with the buffer

ArrayPool.Release(buffer);
```

Kevin pointed out that counting is not necessarily cheap when the DLR is involved. This suggests that it might be better for the library to make a guess at the size of the output span (probably based on the width of rows already written) and retry when it's not big enough.

```csharp
// copy the cells into the output span and return the count
int GetCellsForDynamicRow(in WriteContext writeContext, object row, Span<DynamicCellValue> output);
```

Library code:

```csharp
var buffer = ArrayPool.Get(GuessCellCount());
var count = describer.GetCellsForDynamicRow(writeContext, row, buffer.AsSpan());

if (count > buffer.Length)
{
    // oops, not enough space in the buffer
    ArrayPool.Release(buffer);
    buffer = ArrayPool.Get(count);
    describer.GetCellsForDynamicRow(writeContext, row, buffer.AsSpan().Slice(0, count));
}

// do something with the buffer

ArrayPool.Release(buffer);
```

This way you only have to make multiple passes in the unlikely case that the row is longer than previous rows. It does make the `ITypeDescriber` implementation a little bit messier (it has to be prepared for the case that the span isn't big enough).

**Comment by kevin-montrose** [comment]
I'm planning on trying out this suggestion this weekend, now that #21 is finished.

**Comment by kevin-montrose** [comment]
[First whack on this branch](https://github.com/kevin-montrose/Cesil/tree/issue-6/ienumerable-alternative).

Still needs a little more work, in particular it currently guesses 8-cells per-row which is silly.  There are a few other allocations that can get nuked along with this change as well, I think.

**Comment by kevin-montrose** [comment]
@benjamin-hodgson [proper change as a PR now](https://github.com/kevin-montrose/Cesil/pull/24)

One thing I'm mulling over before merging - I'm pulling the `Span<DynamicCellValue>` out of an [`ArrayPool<DynamicCellValue>`](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.arraypool-1?view=netcore-3.0) (now added to [`Options`](https://github.com/kevin-montrose/Cesil/blob/13af460fdb613f2a77126bf4a7f7f653b14a1ea7/Cesil/Configuration/Options.cs#L181)), but I _could_ take a [`MemoryPool<DynamicCellValue>`](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.memorypool-1?view=netcore-3.0).  I went with `ArrayPool<T>` just 'cause that's where my head was after our chat.

I kind of like using `MemoryPool<T>` since `IMemoryOwner<T>` is a little nicer to work with.  I'd have to give it a proper name on `Options` I supposed, can't have two `MemoryPools`.  Unlike `MemoryPool<char>` it's not really possible for a consumer to back the provided `Span<DynamicCellValue>`s with anything but arrays though.

Any thoughts?

**Comment by benjamin-hodgson** [comment]
I _think_ the default memory pool is just a wrapper for an array pool anyway.

**Comment by benjamin-hodgson** [comment]
I can imagine there being a use case for backing a `MemoryPool` by an arena some other sort of bump allocator

**Comment by kevin-montrose** [comment]
Yeah, default `MemoryPool<T>` delegates to `ArrayPool<T>`.  A meaningful difference did occur to me though, a `MemoryPool<T>` lets you serve multiple requests out of a single array, whereas `ArrayPool<T>` you have to hand back a unique array on each call (until they're returned anyway).

**Comment by kevin-montrose** [comment]
#24 has now been merged into `vNext`

**Comment by benjamin-hodgson** [comment]
@kevin-montrose  The default `MemoryPool` allocates the `IMemoryOwner` when you call `Rent`. https://github.com/dotnet/runtime/blob/3155ca2dfa20e11949f24e439b54ba1816be3c22/src/libraries/System.Memory/src/System/Buffers/ArrayMemoryPool.cs#L22

**Comment by kevin-montrose** [comment]
@benjamin-hodgson yeah, that's not great.  The interface is more flexible, but the more I look at the implementation the more I'm tempted to actually implement a custom `MemoryPool<T>`...

**Comment by kevin-montrose** [comment]
This has shipped.
